#!/usr/bin/env node
/**
 * Generates src/styles/themes.css and the FAMILIES array for ThemeContext.jsx
 * from a single families JSON file, so the CSS and the picker cannot disagree.
 *
 *   node scripts/build-themes.mjs <families.json>
 *
 * Input: [{ key, label, light: {seeds…}, dark: {seeds…} }]
 * where seeds = { bg, text, muted, primary, primaryHover, secondary, onPrimary }
 *
 * Emits the CSS to disk and prints the JS array to stdout for pasting.
 * `npm run audit:themes` then verifies contrast and that the two agree.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(here, '..', 'src', 'styles', 'themes.css');

const src = process.argv[2];
if (!src) {
  console.error('usage: node scripts/build-themes.mjs <families.json>');
  process.exit(2);
}

const families = JSON.parse(fs.readFileSync(src, 'utf8'));

const rgbTriplet = (hex) => {
  let h = hex.replace('#', '');
  if (h.length === 3) h = h.split('').map(c => c + c).join('');
  return [0, 2, 4].map(i => parseInt(h.slice(i, i + 2), 16)).join(', ');
};

const wrap = (text, width, indent) => {
  const words = String(text).split(' ');
  const out = [];
  let line = '';
  for (const w of words) {
    if ((line + ' ' + w).trim().length > width) { out.push(line.trim()); line = w; }
    else line += ' ' + w;
  }
  if (line.trim()) out.push(line.trim());
  return out.map(l => indent + l).join('\n');
};

const seeds = (p) => [
  `  --bg-color: ${p.bg};`,
  `  --text-main: ${p.text};`,
  `  --text-muted: ${p.muted};`,
  `  --primary: ${p.primary};`,
  `  --primary-hover: ${p.primaryHover};`,
  `  --secondary: ${p.secondary};`,
  `  --on-primary: ${p.onPrimary};`,
  `  --primary-rgb: ${rgbTriplet(p.primary)};`,
].join('\n');

const missing = families.filter(f => !f.light || !f.dark);
if (missing.length) {
  console.error('ERROR — every family needs both variants. Missing:');
  missing.forEach(f => console.error(`  ${f.key}: ${!f.light ? 'light' : ''}${!f.dark ? 'dark' : ''}`));
  process.exit(1);
}

const base = families.find(f => f.key === 'azure') || families[0];

const header = `/* ==========================================================================
   DFCCI Threshold — Theme definitions (single source of truth)
   --------------------------------------------------------------------------
   GENERATED by scripts/build-themes.mjs — edit the source JSON, not this file.

   A theme is a FAMILY (an identity) and is independent of MODE. Every family
   ships a light and a dark variant:

     :root[data-theme="aurora"]        light variant
     :root.dark[data-theme="aurora"]   dark variant

   The mode class lives on <html> alongside data-theme, so tokens.css inverts
   elevation once for ':root.dark' rather than listing every dark theme.

   A variant declares only these eight seeds; every other colour in the app is
   derived from them by tokens.css. All are verified at WCAG AA (>= 4.5:1) on
   six pairs — run \`npm run audit:themes\`.
   ========================================================================== */

/* ── Fallback, used only if the bootstrap script in index.html never runs ── */
:root {
${seeds(base.light)}
}

:root.dark {
${seeds(base.dark)}
}
`;

const lightBlocks = families.map(f => {
  const note = f.light.rationale || f.light.character || '';
  return `${note ? `/* ${f.label} — light\n${wrap(note, 70, '   ')} */\n` : `/* ${f.label} — light */\n`}` +
    `:root[data-theme="${f.key}"] {\n${seeds(f.light)}\n}`;
}).join('\n\n');

const darkBlocks = families.map(f => {
  const note = f.dark.rationale || f.dark.character || '';
  return `${note ? `/* ${f.label} — dark\n${wrap(note, 70, '   ')} */\n` : `/* ${f.label} — dark */\n`}` +
    `:root.dark[data-theme="${f.key}"] {\n${seeds(f.dark)}\n}`;
}).join('\n\n');

const css = [
  header,
  '\n/* ══════════════════════════════════════════════════════════════════════════',
  '   LIGHT VARIANTS',
  '   ══════════════════════════════════════════════════════════════════════════ */\n',
  lightBlocks,
  '\n/* ══════════════════════════════════════════════════════════════════════════',
  '   DARK VARIANTS — higher specificity, so these win whenever .dark is set',
  '   ══════════════════════════════════════════════════════════════════════════ */\n',
  darkBlocks,
  '',
].join('\n');

fs.writeFileSync(outFile, css);
console.error(`themes.css written — ${families.length} families, ${families.length * 2} variants`);

// JS registry for ThemeContext.jsx
const pad = (s, n) => String(s).padEnd(n);
console.log('export const FAMILIES = [');
for (const f of families) {
  console.log(
    `  { key: ${pad(`'${f.key}',`, 12)} label: ${pad(`'${f.label}',`, 13)}` +
    ` light: ['${f.light.bg}', '${f.light.primary}'],` +
    ` dark: ['${f.dark.bg}', '${f.dark.primary}'] },`
  );
}
console.log('];');
